
 // This code was generated by a tool. Any changes made manually will be lost
 // the next time this code is regenerated.
 // 
 
using System;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyTitle("OpenBVE")]
[assembly: AssemblyProduct("OpenBVE")]
[assembly: AssemblyCopyright("The OpenBVE Project")]
[assembly: ComVisible(false)]
[assembly: AssemblyVersion("1.7.1800.740")]
[assembly: AssemblyInformationalVersion("1.7.1800.740-kohai")]
[assembly: AssemblyFileVersion("1.7.1800.740")]
[assembly: CLSCompliant(false)]
[assembly: InternalsVisibleTo("RouteManager2")]

namespace OpenBve {
	internal static partial class Program {
		internal const string VersionSuffix = "";
	}
}

